import { useState } from 'react';
import { motion } from 'framer-motion';
import { User, Bell, Shield, CreditCard, Camera, CheckCircle, Star, Edit3, Phone, Mail, Calendar } from 'lucide-react';
import Navbar from '../components/layout/Navbar';
import { mockUserProfile, mockPersonalityProfiles } from '../data/mockData';

const tabs = [{ id: 'personal', label: 'Personal Info', icon: User }, { id: 'assessment', label: 'Assessment', icon: Star }, { id: 'privacy', label: 'Privacy', icon: Shield }, { id: 'notifications', label: 'Notifications', icon: Bell }, { id: 'subscription', label: 'Subscription', icon: CreditCard }];

export default function ProfilePage() {
  const [activeTab, setActiveTab] = useState('personal');
  const user = mockUserProfile;
  const profile = mockPersonalityProfiles[user.personalityType];

  return (
    <div className="min-h-screen bg-calm-50">
      <Navbar isLoggedIn />
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-12">
        <div className="grid lg:grid-cols-4 gap-6">
          <div className="lg:col-span-1">
            <div className="bg-white rounded-2xl border border-calm-100 shadow-sm p-5 text-center mb-4">
              <div className="relative inline-block mb-3"><img src={user.avatar} alt={user.name} className="w-20 h-20 rounded-2xl object-cover" /><button className="absolute -bottom-1 -right-1 w-7 h-7 bg-primary-600 rounded-full flex items-center justify-center text-white hover:bg-primary-700 transition-colors"><Camera size={13} /></button></div>
              <h2 className="font-bold text-calm-900">{user.name}</h2>
              <p className="text-xs text-calm-500 mt-1">Member since {user.joinDate}</p>
              <div className="mt-3 flex items-center justify-center gap-1.5"><div className="badge-primary text-xs">{user.subscription}</div></div>
            </div>

            <div className="bg-white rounded-2xl border border-calm-100 shadow-sm overflow-hidden">{tabs.map(({ id, label, icon: Icon }) => (<button key={id} onClick={() => setActiveTab(id)} className={`w-full flex items-center gap-3 px-4 py-3.5 text-sm transition-all text-left ${activeTab === id ? 'bg-primary-50 text-primary-700 font-medium border-l-2 border-primary-600' : 'text-calm-600 hover:bg-calm-50'}`}><Icon size={16} />{label}</button>))}</div>
          </div>

          <div className="lg:col-span-3">
            <motion.div key={activeTab} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }} className="bg-white rounded-2xl border border-calm-100 shadow-sm p-6">
              {activeTab === 'personal' && (<div><div className="flex items-center justify-between mb-6"><h3 className="font-bold text-calm-900">Personal Information</h3><button className="flex items-center gap-1.5 text-sm text-primary-600 hover:text-primary-700"><Edit3 size={14} />Edit</button></div><div className="grid sm:grid-cols-2 gap-5">{[{ label: 'Full Name', value: user.name, icon: User }, { label: 'Phone', value: user.phone, icon: Phone }, { label: 'Email', value: user.email, icon: Mail }, { label: 'Age', value: `${user.age} years`, icon: Calendar }, { label: 'Gender', value: user.gender, icon: User }, { label: 'Status', value: user.relationshipStatus, icon: User }].map(({ label, value, icon: Icon }) => (<div key={label} className="bg-calm-50 rounded-xl p-4"><p className="text-xs text-calm-400 mb-1 flex items-center gap-1.5"><Icon size={11} />{label}</p><p className="font-medium text-calm-800">{value}</p></div>))}</div></div>)}

              {activeTab === 'assessment' && profile && (<div><h3 className="font-bold text-calm-900 mb-6">Assessment Results</h3><div className="bg-gradient-to-br from-primary-600 to-teal-600 rounded-2xl p-6 text-white mb-5"><div className="flex items-center gap-3 mb-3"><div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center"><Star size={22} /></div><div><p className="text-primary-100 text-sm">Personality Type</p><h2 className="text-2xl font-bold">{profile.type}</h2></div><span className="ml-auto bg-white/20 text-white text-sm font-mono px-3 py-1 rounded-full">{profile.code}</span></div><p className="text-primary-100 text-sm leading-relaxed">{profile.description}</p></div><div className="grid sm:grid-cols-2 gap-4"><div className="bg-teal-50 rounded-xl p-4"><h4 className="font-semibold text-teal-800 mb-3 text-sm">Strengths</h4><ul className="space-y-2">{profile.strengths.map((s: string) => (<li key={s} className="flex items-center gap-2 text-sm text-teal-700"><CheckCircle size={13} className="text-teal-500" />{s}</li>))}</ul></div><div className="bg-primary-50 rounded-xl p-4"><h4 className="font-semibold text-primary-800 mb-3 text-sm">Communication Style</h4><p className="text-sm text-primary-700 leading-relaxed">{profile.communicationStyle}</p><div className="mt-4"><p className="font-semibold text-primary-800 mb-2 text-sm">Emotional Tendencies</p><p className="text-sm text-primary-700 leading-relaxed">{profile.emotionalTendencies}</p></div></div></div><button className="mt-5 w-full py-3 border-2 border-dashed border-calm-200 rounded-xl text-sm text-calm-500 hover:border-primary-300 hover:text-primary-600 transition-all">Update Assessment</button></div>)}

              {activeTab === 'privacy' && (<div><h3 className="font-bold text-calm-900 mb-6">Privacy Settings</h3><div className="space-y-4">{[{ title: 'Share data with psychologists', desc: 'Selected psychologists can view your profile', enabled: true }, { title: 'Save conversation history', desc: 'For personalized experience improvement', enabled: true }, { title: 'Anonymous AI improvement', desc: 'Fully anonymous data to improve models', enabled: false }, { title: 'Public profile', desc: 'Other users can see your public profile', enabled: false }].map(({ title, desc, enabled }) => (<div key={title} className="flex items-center justify-between p-4 bg-calm-50 rounded-xl"><div><p className="text-sm font-medium text-calm-800">{title}</p><p className="text-xs text-calm-500">{desc}</p></div><div className={`w-11 h-6 rounded-full transition-colors cursor-pointer ${enabled ? 'bg-primary-500' : 'bg-calm-300'}`}><div className="w-5 h-5 bg-white rounded-full shadow-sm mt-0.5" style={{ marginLeft: enabled ? '1px' : '21px', transition: 'margin 0.2s' }} /></div></div>))}</div><div className="mt-6 p-4 bg-warning-50 border border-warning-200 rounded-xl"><p className="text-sm font-semibold text-warning-800 mb-1">Delete Account</p><p className="text-xs text-warning-700 mb-3">This action is irreversible and all your data will be deleted.</p><button className="text-xs text-error-600 border border-error-300 px-4 py-2 rounded-xl hover:bg-error-50 transition-colors">Request Account Deletion</button></div></div>)}

              {activeTab === 'notifications' && (<div><h3 className="font-bold text-calm-900 mb-6">Notification Settings</h3><div className="space-y-4">{[{ title: 'Session reminders', desc: 'Before sessions with psychologists', enabled: true }, { title: 'Psychologist messages', desc: 'Messages received from psychologists', enabled: true }, { title: 'Daily mood reminder', desc: 'Reminder to log daily status', enabled: true }, { title: 'Wellness suggestions', desc: 'Recommendations based on your profile', enabled: false }, { title: 'Newsletter', desc: 'Therapino news and new content', enabled: false }].map(({ title, desc, enabled }) => (<div key={title} className="flex items-center justify-between p-4 bg-calm-50 rounded-xl"><div><p className="text-sm font-medium text-calm-800">{title}</p><p className="text-xs text-calm-500">{desc}</p></div><div className={`w-11 h-6 rounded-full transition-colors cursor-pointer ${enabled ? 'bg-primary-500' : 'bg-calm-300'}`}><div className="w-5 h-5 bg-white rounded-full shadow-sm mt-0.5" style={{ marginLeft: enabled ? '1px' : '21px', transition: 'margin 0.2s' }} /></div></div>))}</div></div>)}

              {activeTab === 'subscription' && (<div><h3 className="font-bold text-calm-900 mb-6">Subscription</h3><div className="bg-gradient-to-br from-primary-600 to-teal-600 rounded-2xl p-6 text-white mb-6"><div className="flex items-center justify-between mb-3"><div><p className="text-primary-100 text-sm">Current Plan</p><h3 className="text-2xl font-bold">{user.subscription}</h3></div><Star size={32} className="text-warning-300" /></div><p className="text-primary-100 text-sm">Expires: July 15, 2024</p><div className="mt-4 h-1.5 bg-primary-400/50 rounded-full"><div className="h-full bg-white rounded-full w-3/4" /></div><p className="text-primary-200 text-xs mt-1">21 days remaining</p></div><div className="space-y-3"><div className="flex justify-between p-4 bg-calm-50 rounded-xl text-sm"><span className="text-calm-600">Online psychologist sessions</span><span className="font-medium text-calm-800">2/month (0 left)</span></div><div className="flex justify-between p-4 bg-calm-50 rounded-xl text-sm"><span className="text-calm-600">AI conversations</span><span className="font-medium text-calm-800">Unlimited</span></div><div className="flex justify-between p-4 bg-calm-50 rounded-xl text-sm"><span className="text-calm-600">Support</span><span className="font-medium text-calm-800">Priority</span></div></div><div className="mt-5 flex gap-3"><button className="flex-1 btn-primary">Upgrade to Premium</button><button className="px-5 py-3 border border-calm-200 rounded-xl text-sm text-calm-600 hover:bg-calm-50">Cancel</button></div></div>)}
            </motion.div>
          </div>
        </div>
      </div>
    </div>
  );
}
