import { motion } from 'framer-motion';
import { CircleAlert as AlertCircle, TriangleAlert as AlertTriangle, Info, Search, ChevronRight } from 'lucide-react';
import RTTSidebar from '../../components/dashboard/RTTSidebar';
import { mockChildhoodEvents, mockRTTClients } from '../../data/mockData';

const fadeInUp = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5 } } };
const stagger = { visible: { transition: { staggerChildren: 0.08 } } };

export default function RTTChildhoodPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-calm-50 to-teal-50">
      <RTTSidebar />
      <div className="ml-64 p-6">
        <motion.div initial="hidden" animate="visible" variants={stagger}>
          <motion.div variants={fadeInUp} className="mb-6">
            <h1 className="text-2xl font-bold text-calm-900">Childhood Events Explorer</h1>
            <p className="text-calm-500 mt-1">AI-inferred contributing experiences from early life</p>
          </motion.div>

          {/* Critical Disclaimer */}
          <motion.div variants={fadeInUp} className="mb-6 p-5 bg-error-50 border-2 border-error-300 rounded-xl">
            <div className="flex items-start gap-3">
              <AlertTriangle size={24} className="text-error-500 mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="font-bold text-error-800 mb-1">Important: These are AI Hypotheses, Not Verified Facts</h3>
                <p className="text-sm text-error-700 leading-relaxed">
                  The events and experiences shown below are <strong>inferred patterns</strong> generated by AI analysis
                  of client language, emotional expressions, and belief structures. They are <strong>probable contributing
                  factors</strong> that should be explored and validated during RTT sessions. Never assume these as
                  confirmed historical facts without clinical verification.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Secondary Info */}
          <motion.div variants={fadeInUp} className="mb-6 p-4 bg-primary-50 border border-primary-200 rounded-xl">
            <div className="flex items-start gap-3">
              <Info size={18} className="text-primary-500 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-primary-800">
                These patterns are derived from AI analysis of client expressions, emotional triggers, and limiting belief themes.
                Use them as starting points for RTT regression work.
              </p>
            </div>
          </motion.div>

          {/* Childhood Events Grid */}
          <motion.div variants={stagger} initial="hidden" animate="visible" className="grid md:grid-cols-2 gap-5 mb-8">
            {mockChildhoodEvents.map((event) => (
              <motion.div key={event.id} variants={fadeInUp} className="bg-white rounded-2xl border border-calm-100 p-6 shadow-sm">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-warning-100 flex items-center justify-center">
                      <AlertCircle size={20} className="text-warning-600" />
                    </div>
                    <div>
                      <h3 className="font-bold text-calm-900">{event.type}</h3>
                      <p className="text-xs text-calm-500">{event.confidence}% detection confidence</p>
                    </div>
                  </div>
                  <div className={`w-10 h-10 rounded-xl flex items-center justify-center text-sm font-bold ${
                    event.confidence >= 80 ? 'bg-error-100 text-error-600' :
                    event.confidence >= 70 ? 'bg-warning-100 text-warning-600' :
                    'bg-primary-100 text-primary-600'
                  }`}>
                    {event.confidence}%
                  </div>
                </div>

                <p className="text-sm text-calm-600 leading-relaxed mb-4">{event.description}</p>

                <div className="p-3 bg-calm-50 rounded-xl">
                  <p className="text-xs text-calm-500 mb-2">Supporting Indicators:</p>
                  <div className="space-y-1.5">
                    {event.indicators.map((indicator) => (
                      <div key={indicator} className="flex items-center gap-2 text-xs text-calm-700">
                        <Search size={10} className="text-calm-400" />
                        {indicator}
                      </div>
                    ))}
                  </div>
                </div>

                <div className="mt-4 pt-4 border-t border-calm-100 flex items-center justify-between">
                  <span className="text-xs text-calm-400 italic">
                    {event.confidence >= 80 ? 'High probability' :
                     event.confidence >= 70 ? 'Moderate probability' : 'Early pattern detection'}
                  </span>
                  <button className="text-xs text-teal-600 font-medium flex items-center gap-1 hover:text-teal-700">
                    Explore in Session <ChevronRight size={12} />
                  </button>
                </div>
              </motion.div>
            ))}
          </motion.div>

          {/* Session Recommendations */}
          <motion.div variants={fadeInUp} className="bg-white rounded-2xl border border-calm-100 p-6 shadow-sm">
            <h3 className="font-bold text-calm-900 mb-4">RTT Session Planning Recommendations</h3>
            <div className="grid md:grid-cols-3 gap-4">
              <div className="p-4 bg-error-50 rounded-xl border border-error-100">
                <p className="text-xs text-error-600 font-medium mb-2">Priority: High</p>
                <p className="text-sm text-error-800">Childhood criticism and lack of validation patterns suggest deep self-worth regression work for multiple clients.</p>
              </div>
              <div className="p-4 bg-warning-50 rounded-xl border border-warning-100">
                <p className="text-xs text-warning-600 font-medium mb-2">Priority: Medium</p>
                <p className="text-sm text-warning-800">Emotional neglect patterns indicate need for inner child work and reparenting exercises during sessions.</p>
              </div>
              <div className="p-4 bg-primary-50 rounded-xl border border-primary-100">
                <p className="text-xs text-primary-600 font-medium mb-2">Exploration Focus</p>
                <p className="text-sm text-primary-800">Relationship trauma patterns suggest exploration of early attachment figures and trust development work.</p>
              </div>
            </div>
          </motion.div>

          {/* Data Source Note */}
          <motion.div variants={fadeInUp} className="mt-6 p-4 bg-calm-100 rounded-xl text-center">
            <p className="text-xs text-calm-500">
              Data derived from AI analysis of {mockRTTClients.length} active clients. Patterns are updated weekly based on new session content.
            </p>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}
